config/routes.rb
Rails.application.routes.draw do
  resources :microposts
  resources :users
  root "users#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user
  validates :content, presence: true
  validates :content, length: { maximum: 140 }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :microposts
  validates :name, presence: true
  validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  # GET /microposts
  def index
    @microposts = Micropost.all
  end

  # GET /microposts/1
  def show
    @micropost = Micropost.find(params[:id])
  end

  # GET /microposts/new
  def new
    @micropost = Micropost.new
  end

  # GET /microposts/1/edit
  def edit
    @micropost = Micropost.find(params[:id])
  end

  # POST /microposts
  def create
    @micropost = Micropost.new(micropost_params)

    if @micropost.save
      redirect_to @micropost, notice: 'Micropost was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /microposts/1
  def update
    @micropost = Micropost.find(params[:id])
    if @micropost.update(micropost_params)
      redirect_to @micropost, notice: 'Micropost was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /microposts/1
  def destroy
    @micropost = Micropost.find(params[:id])
    @micropost.destroy
    redirect_to microposts_url, notice: 'Micropost was successfully destroyed.'
  end

  private
    # Only allow a trusted parameter "white list" through.
    def micropost_params
      params.require(:micropost).permit(:content, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  def index
    @users = User.all
  end

  # GET /users/1
  def show
    @user = User.find(params[:id])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to @user, notice: 'User was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /users/1
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /users/1
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_url, notice: 'User was successfully destroyed.'
  end

  private
    # Only allow a trusted parameter "white list" through.
    def user_params
      params.require(:user).permit(:name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{charset: "utf-8"}
    %meta{content: "IE=edge", "http-equiv" => "X-UA-Compatible"}
    %meta{content: "width=device-width, initial-scale=1", name: "viewport"}
    %meta{content: "", name: "description"}
    %meta{content: "", name: "author"}
    %title
      = ToyApp

    / HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries
    /[if lt IE 9]
      = javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js"

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body{class: "controller-#{controller_name} action-#{action_name}"}
    %nav.navbar.navbar-inverse.navbar-fixed-top{role: "navigation"}
      .container
        .navbar-header
          %button.navbar-toggle.collapsed{type: "button", data: {toggle: "collapse", target: "#navbar"}, aria: {expanded: "false", controls: "navbar"} }
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          = link_to users_path, class: "navbar-brand" do
            ToyApp
        #navbar.collapse.navbar-collapse
          %ul.nav.navbar-nav
            %li.active
              = link_to "Home", users_path
    .container
      - flash.each do |name, msg|
        = content_tag :div, class: "alert alert-#{name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do
          %button.close{type: "button", data: {dismiss: "alert"} }
            %span{aria: {hidden: "true"} } &times;
            %span.sr-only Close
          = msg
      = yield

app/views/microposts/_form.html.haml
= form_for @micropost, html: { class: "form-horizontal", role: "form" } do |f|
  -if @micropost.errors.any?
    .alert.alert-danger.alert-dismissable{role: "alert"}
      %button.close{type: "button", data: {dismiss: "alert"} }
        %span{aria: {hidden: "true"} } &times;
        %span.sr-only Close
      %h4= "#{pluralize(@micropost.errors.count, "error")} prohibited this micropost from being saved:"

      %ul
        - @micropost.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :content, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_area :content, class: 'form-control'
  .form-group
    = f.label :user_id, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.number_field :user_id, class: 'form-control'
  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit class: 'btn btn-primary'

app/views/microposts/edit.html.haml
.page-header
  = link_to microposts_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to @micropost, class: 'btn btn-primary' do
    %span.glyphicon.glyphicon-info-sign
    Show
  %h1 Editing micropost

= render 'form'

app/views/microposts/index.html.haml
.page-header
  = link_to new_micropost_path, class: 'btn btn-primary' do
    %span.glyphicon.glyphicon-plus
    New Micropost
%h1 Listing microposts

.table-responsive
  %table.table.table-striped.table-bordered.table-hover
    %thead
      %tr
        %th Content
        %th User
        %th{colspan: 3}

    %tbody.table-body
      - @microposts.each do |micropost|
        %tr
          %td
            = micropost.content
          %td
            = micropost.user_id
          %td
            = link_to 'Destroy', micropost, method: :delete, data: {confirm: 'Are you sure?'}

app/views/microposts/new.html.haml
.page-header
  = link_to microposts_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  %h1 New micropost

= render 'form'

app/views/microposts/show.html.haml
.page-header
  = link_to microposts_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to edit_micropost_path(@micropost), class: 'btn btn-primary' do
    %span.glyphicon.glyphicon-pencil
    Edit
  %h1 Show micropost

%dl.dl-horizontal
  %dt Content:
  %dd= @micropost.content
  %dt User:
  %dd= @micropost.user_id

app/views/users/_form.html.haml
= form_for @user, html: { class: "form-horizontal", role: "form" } do |f|
  -if @user.errors.any?
    .alert.alert-danger.alert-dismissable{role: "alert"}
      %button.close{type: "button", data: {dismiss: "alert"} }
        %span{aria: {hidden: "true"} } &times;
        %span.sr-only Close
      %h4= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"

      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :name, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :name, class: 'form-control'
  .form-group
    = f.label :email, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :email, class: 'form-control'
  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit class: 'btn btn-primary'

app/views/users/edit.html.haml
.page-header
  = link_to users_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to @user, class: 'btn btn-primary' do
    %span.glyphicon.glyphicon-info-sign
    Show
  %h1 Editing user

= render 'form'

app/views/users/index.html.haml
.page-header
  = link_to new_user_path, class: 'btn btn-primary' do
    %span.glyphicon.glyphicon-plus
    New User
%h1 Listing users

.table-responsive
  %table.table.table-striped.table-bordered.table-hover
    %thead
      %tr
        %th Name
        %th Email
        %th{colspan: 3}


    %tbody.table-body
      - @users.each do |user|
        %tr
          %td
            = user.name
          %td
            = user.email
          %td
            = link_to 'Show', user
          %td
            = link_to 'Edit', edit_user_path(user) #if it's just user, it will be a two step process. It does not go to edit user page directly
          %td
            = link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }

app/views/users/new.html.haml
.page-header
  = link_to users_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  %h1 New user

= render 'form'

app/views/users/show.html.haml
.page-header
  = link_to users_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to edit_user_path(@user), class: 'btn btn-primary' do
    %span.glyphicon.glyphicon-pencil
    Edit
  %h1 Show user

%dl.dl-horizontal
  %dt Name:
  %dd= @user.name
  %dt Email:
  %dd= @user.email